name: Git Checks

on: [push]

jobs:
  block-fixup:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@v1.1.1